title: Ilya Lyapin's portfolio
description: Hello there! Welcome to my porfolio. Yeah, very unexpected as if the name doesn't already imply that :). But still, here you will find all that is worth knowing about me before offering a job. And a little more, probably
theme: just-the-docs

url: https://esquire-of-rohan.github.io


